### ISSUE TITLE
Rotating Emojis

### ISSUE THREAD

**Issue by udarts** [pd95/CS193p-EmojiArt#1]
How can I rotate Emojis?

I have been trying to create it, but unsuccesfull.

Any assistance?

**Comment by pd95** [comment]
Do you mean Emoji rotation as an animation? Eg like in [Memorize](https://github.com/pd95/CS193p-Memorize)?
Or rotation as a result of a gesture?

**Comment by udarts** [comment]
Sorry for the unclarity, it is the rotation gesture. Not flipping.

Thanks

**Comment by pd95** [comment]
You will have to add a `RotationGesture` (see [Hacking with Swift](https://www.hackingwithswift.com/books/ios-swiftui/how-to-use-gestures-in-swiftui) for a general introduction to gesture handling).

You will have to add some rotation state of type Double to [Emoji struct](https://github.com/pd95/CS193p-EmojiArt/blob/437b796b72140b85f1cb53bb0ff5c34152fbdcb8/EmojiArt/EmojiArt.swift#L19), then add a rotation intent similar to `scaleEmoji` to [EmojiArtDocument](https://github.com/pd95/CS193p-EmojiArt/blob/437b796b72140b85f1cb53bb0ff5c34152fbdcb8/EmojiArt/EmojiArtDocument.swift#L81) and finally add the rotation effect to the [Emoji `Text` representation](https://github.com/pd95/CS193p-EmojiArt/blob/437b796b72140b85f1cb53bb0ff5c34152fbdcb8/EmojiArt/EmojiArtDocumentView.swift#L60) and the rotation gesture similar to `zoomGesture` to [EmojiArtDocumentView](https://github.com/pd95/CS193p-EmojiArt/blob/437b796b72140b85f1cb53bb0ff5c34152fbdcb8/EmojiArt/EmojiArtDocumentView.swift#L161).

I hope this clarifies the general idea.

**Comment by pd95** [comment]
As you see, I've implemented a change (see 22cab99) which adds this feature.
As we already have scaling as a multitouch gesture we have to register the rotation gesture as a "simultaneous gesture".

(I tested it only in the iPad simulator so far)

**Comment by udarts** [comment]
Hi @pd95,

I was working in a similar direction, only looking at different code, I will need to adjust certain code to have it work properly for me. But thanks for pointing me in the right direction.

Thanks again.

**Comment by udarts** [comment]
Closing the issue, thanks for your help.
